/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ConsumerRole;

import Business.EcoSystem;
import Business.Employee.Consumer.Consumer;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GlobalEnterprise.GlobalEnterprise;
import Business.LocalEnergy.CommunitySensor;
import Business.Organization.GlobalEnergy.ConsumerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Billing.BillValueToConsumer;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author neera
 */
public class ViewCurrentMonthBillJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private ConsumerOrganization organization;
    private Enterprise enterprise;
    private Consumer consumer;
    private EcoSystem business;
    private CommunitySensor commSensor;

    /**
     * Creates new form ViewCurrentMonthBillJPanel
     */
    public ViewCurrentMonthBillJPanel(JPanel userProcessContainer, UserAccount userAccount, Consumer consumer, ConsumerOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.consumer = consumer;
        this.business = business;
        this.userAccount = userAccount;
        populateData();
    }

    public void populateData() {
        lblConsumerName.setText(consumer.getName());
        lblConsumerAddress.setText(consumer.getAddress());
        lblConsumerId.setText(consumer.getConsumerId());
        

    }

    public String MonthStartAndEndDate() {
        int month = month = new GregorianCalendar().getActualMaximum(Calendar.DAY_OF_MONTH);
        Calendar gc = new GregorianCalendar();
        gc.set(Calendar.MONTH, month);
        gc.set(Calendar.DAY_OF_MONTH, 1);
        Date monthStart = gc.getTime();
        gc.add(Calendar.MONTH, 1);
        gc.add(Calendar.DAY_OF_MONTH, -1);
        Date monthEnd = gc.getTime();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

        System.out.println("Calculated month start date : " + format.format(monthStart));
        System.out.println("Calculated month end date : " + format.format(monthEnd));
        return format.format(monthStart) + " to " + format.format(monthEnd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblConsumerName = new javax.swing.JLabel();
        lblConsumerAddress = new javax.swing.JLabel();
        lblConsumerId = new javax.swing.JLabel();
        lblBillAmount = new javax.swing.JLabel();
        lblEnergyConsumption = new javax.swing.JLabel();
        lblMonthStartAndEndDate = new javax.swing.JLabel();
        btnGetMyMonthlyBill = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Consumer Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 81, -1, -1));

        jLabel2.setText("Consumer Address:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 121, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Monthly Bill");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 16, -1, -1));

        jLabel5.setText("Consumer Number:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 197, -1, -1));

        jLabel7.setText("Bill Period(From Date and To Date):");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 275, -1, -1));

        jLabel8.setText("Energy Consumption:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 330, -1, -1));

        jLabel9.setText("BILL AMOUNT FOR 30 DAYS @ 0.011$ PER WATT-HOUR");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 384, -1, -1));

        jButton1.setText("<<back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 451, -1, -1));

        lblConsumerName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConsumerName.setText("<value>");
        add(lblConsumerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 79, -1, -1));

        lblConsumerAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConsumerAddress.setText("<value>");
        add(lblConsumerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 119, -1, -1));

        lblConsumerId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConsumerId.setText("<value>");
        add(lblConsumerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 195, -1, -1));

        lblBillAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBillAmount.setText("<value>");
        add(lblBillAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 382, -1, -1));

        lblEnergyConsumption.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnergyConsumption.setText("<value>");
        add(lblEnergyConsumption, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 328, -1, -1));

        lblMonthStartAndEndDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMonthStartAndEndDate.setText("<value>");
        add(lblMonthStartAndEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 273, -1, -1));

        btnGetMyMonthlyBill.setText("Get My bill and consumption");
        btnGetMyMonthlyBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetMyMonthlyBillActionPerformed(evt);
            }
        });
        add(btnGetMyMonthlyBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 451, 270, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("KWatts");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 328, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("$");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 20, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGetMyMonthlyBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetMyMonthlyBillActionPerformed
        // TODO add your handling code here:
        for (WorkRequest wr : userAccount.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof BillValueToConsumer) {
                int consumption = ((BillValueToConsumer) wr).getConsumptionValue();
                double bill = ((BillValueToConsumer) wr).getBillValue();
                if (consumption == 0 || bill == 0) {
                    JOptionPane.showMessageDialog(null, "Bill not generated yet!");
                } else {
                    lblEnergyConsumption.setText(String.valueOf(consumption));
                    lblBillAmount.setText(String.valueOf(bill));
                }
            }
        }

    }//GEN-LAST:event_btnGetMyMonthlyBillActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetMyMonthlyBill;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBillAmount;
    private javax.swing.JLabel lblConsumerAddress;
    private javax.swing.JLabel lblConsumerId;
    private javax.swing.JLabel lblConsumerName;
    private javax.swing.JLabel lblEnergyConsumption;
    private javax.swing.JLabel lblMonthStartAndEndDate;
    // End of variables declaration//GEN-END:variables
}
