package com.smartenergy.spring.pojo;
// Generated Apr 23, 2016 4:00:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.smartenergy.spring.pojo.transientclass.Sensor;

/**
 * Consumer generated by hbm2java
 */
@Entity
@Table(name = "consumer", catalog = "smartenergy5")
public class Consumer implements java.io.Serializable {

	private Sensor sensor;
	private Integer consumerId;
	private Useraccount useraccount;
	private String firstName;
	private String lastName;
	private String addressLine1;
	@Transient
	public Sensor getSensor() {
		return sensor;
	}

	public void setSensor(Sensor sensor) {
		this.sensor = sensor;
	}

	private String addressLine2;
	private String city;
	private String zip;
	private String state;
	private String email;
	private Set<Consumerservicesbilling> consumerservicesbillings = new HashSet<Consumerservicesbilling>(0);
	private Set<Globalconsumptionlist> globalconsumptionlists = new HashSet<Globalconsumptionlist>(0);
	private Set<Localconsumptionlist> localconsumptionlists = new HashSet<Localconsumptionlist>(0);

	public Consumer() {
	}

	public Consumer(String firstName, String addressLine1, String city, String zip, String state, String email) {
		this.firstName = firstName;
		this.addressLine1 = addressLine1;
		this.city = city;
		this.zip = zip;
		this.state = state;
		this.email = email;
	}

	public Consumer(Useraccount useraccount, String firstName, String lastName, String addressLine1,
			String addressLine2, String city, String zip, String state, String email,
			Set<Consumerservicesbilling> consumerservicesbillings, Set<Globalconsumptionlist> globalconsumptionlists,
			Set<Localconsumptionlist> localconsumptionlists) {
		this.useraccount = useraccount;
		this.firstName = firstName;
		this.lastName = lastName;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.zip = zip;
		this.state = state;
		this.email = email;
		this.consumerservicesbillings = consumerservicesbillings;
		this.globalconsumptionlists = globalconsumptionlists;
		this.localconsumptionlists = localconsumptionlists;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ConsumerId", unique = true, nullable = false)
	public Integer getConsumerId() {
		return this.consumerId;
	}

	public void setConsumerId(Integer consumerId) {
		this.consumerId = consumerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId")
	public Useraccount getUseraccount() {
		return this.useraccount;
	}

	public void setUseraccount(Useraccount useraccount) {
		this.useraccount = useraccount;
	}

	@Column(name = "FirstName", nullable = false, length = 20)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LastName", length = 20)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "AddressLine1", nullable = false, length = 40)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "AddressLine2", length = 40)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "City", nullable = false, length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "Zip", nullable = false, length = 5)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "State", nullable = false, length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consumer")
	public Set<Consumerservicesbilling> getConsumerservicesbillings() {
		return this.consumerservicesbillings;
	}

	public void setConsumerservicesbillings(Set<Consumerservicesbilling> consumerservicesbillings) {
		this.consumerservicesbillings = consumerservicesbillings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consumer")
	public Set<Globalconsumptionlist> getGlobalconsumptionlists() {
		return this.globalconsumptionlists;
	}

	public void setGlobalconsumptionlists(Set<Globalconsumptionlist> globalconsumptionlists) {
		this.globalconsumptionlists = globalconsumptionlists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consumer")
	public Set<Localconsumptionlist> getLocalconsumptionlists() {
		return this.localconsumptionlists;
	}

	public void setLocalconsumptionlists(Set<Localconsumptionlist> localconsumptionlists) {
		this.localconsumptionlists = localconsumptionlists;
	}

}
