package com.smartenergy.spring.pojo;
// Generated Apr 23, 2016 4:00:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Consumerservicesbilling generated by hbm2java
 */
@Entity
@Table(name = "consumerservicesbilling", catalog = "smartenergy5")
public class Consumerservicesbilling implements java.io.Serializable {

	private ConsumerservicesbillingId id;
	private Consumer consumer;
	private float localMonthlyEnergyBill;
	private float globalMonthlyEnergyBill;
	private Date fromDate;
	private Date toDate;

	public Consumerservicesbilling() {
	}

	public Consumerservicesbilling(ConsumerservicesbillingId id, Consumer consumer, float localMonthlyEnergyBill,
			float globalMonthlyEnergyBill, Date fromDate, Date toDate) {
		this.id = id;
		this.consumer = consumer;
		this.localMonthlyEnergyBill = localMonthlyEnergyBill;
		this.globalMonthlyEnergyBill = globalMonthlyEnergyBill;
		this.fromDate = fromDate;
		this.toDate = toDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "consumerServicesId", column = @Column(name = "ConsumerServicesId", nullable = false)),
			@AttributeOverride(name = "consumerId", column = @Column(name = "ConsumerId", nullable = false)) })
	public ConsumerservicesbillingId getId() {
		return this.id;
	}

	public void setId(ConsumerservicesbillingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ConsumerId", nullable = false, insertable = false, updatable = false)
	public Consumer getConsumer() {
		return this.consumer;
	}

	public void setConsumer(Consumer consumer) {
		this.consumer = consumer;
	}

	@Column(name = "LocalMonthlyEnergyBill", nullable = false, precision = 12, scale = 0)
	public float getLocalMonthlyEnergyBill() {
		return this.localMonthlyEnergyBill;
	}

	public void setLocalMonthlyEnergyBill(float localMonthlyEnergyBill) {
		this.localMonthlyEnergyBill = localMonthlyEnergyBill;
	}

	@Column(name = "GlobalMonthlyEnergyBill", nullable = false, precision = 12, scale = 0)
	public float getGlobalMonthlyEnergyBill() {
		return this.globalMonthlyEnergyBill;
	}

	public void setGlobalMonthlyEnergyBill(float globalMonthlyEnergyBill) {
		this.globalMonthlyEnergyBill = globalMonthlyEnergyBill;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FromDate", nullable = false, length = 10)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ToDate", nullable = false, length = 10)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

}
