package com.smartenergy.spring.pojo;
// Generated Apr 23, 2016 4:00:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Globalconsumptionlist generated by hbm2java
 */
@Entity
@Table(name = "globalconsumptionlist", catalog = "smartenergy5")
public class Globalconsumptionlist implements java.io.Serializable {

	private GlobalconsumptionlistId id;
	private Globalservices globalservices;
	private Consumer consumer;
	private float powerConsumed;
	private float chargedAmount;
	private Date dateTimePowerConsumed;

	public Globalconsumptionlist() {
	}

	public Globalconsumptionlist(GlobalconsumptionlistId id, Globalservices globalservices, Consumer consumer,
			float powerConsumed, float chargedAmount, Date dateTimePowerConsumed) {
		this.id = id;
		this.globalservices = globalservices;
		this.consumer = consumer;
		this.powerConsumed = powerConsumed;
		this.chargedAmount = chargedAmount;
		this.dateTimePowerConsumed = dateTimePowerConsumed;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "globalConsumptionListId", column = @Column(name = "GlobalConsumptionListId", nullable = false)),
			@AttributeOverride(name = "consumerId", column = @Column(name = "ConsumerId", nullable = false)),
			@AttributeOverride(name = "globalServiceId", column = @Column(name = "GlobalServiceId", nullable = false)),
			@AttributeOverride(name = "globalVendorId", column = @Column(name = "GlobalVendorId", nullable = false)) })
	public GlobalconsumptionlistId getId() {
		return this.id;
	}

	public void setId(GlobalconsumptionlistId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "GlobalServiceId", referencedColumnName = "GlobalServiceId", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "GlobalVendorId", referencedColumnName = "GlobalVendorId", nullable = false, insertable = false, updatable = false) })
	public Globalservices getGlobalservices() {
		return this.globalservices;
	}

	public void setGlobalservices(Globalservices globalservices) {
		this.globalservices = globalservices;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ConsumerId", nullable = false, insertable = false, updatable = false)
	public Consumer getConsumer() {
		return this.consumer;
	}

	public void setConsumer(Consumer consumer) {
		this.consumer = consumer;
	}

	@Column(name = "PowerConsumed", nullable = false, precision = 12, scale = 0)
	public float getPowerConsumed() {
		return this.powerConsumed;
	}

	public void setPowerConsumed(float powerConsumed) {
		this.powerConsumed = powerConsumed;
	}

	@Column(name = "ChargedAmount", nullable = false, precision = 12, scale = 0)
	public float getChargedAmount() {
		return this.chargedAmount;
	}

	public void setChargedAmount(float chargedAmount) {
		this.chargedAmount = chargedAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateTimePowerConsumed", nullable = false, length = 10)
	public Date getDateTimePowerConsumed() {
		return this.dateTimePowerConsumed;
	}

	public void setDateTimePowerConsumed(Date dateTimePowerConsumed) {
		this.dateTimePowerConsumed = dateTimePowerConsumed;
	}

}
