package com.smartenergy.spring.pojo;
// Generated Apr 23, 2016 4:00:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Globalservices generated by hbm2java
 */
@Entity
@Table(name = "globalservices", catalog = "smartenergy5")
public class Globalservices implements java.io.Serializable {

	private GlobalservicesId id;
	private Globalenergyvendor globalenergyvendor;
	private String globalServiceName;
	private String globalDescription;
	private float ratePerPower;
	private Set<Globalconsumptionlist> globalconsumptionlists = new HashSet<Globalconsumptionlist>(0);

	public Globalservices() {
	}

	public Globalservices(GlobalservicesId id, Globalenergyvendor globalenergyvendor, String globalServiceName,
			float ratePerPower) {
		this.id = id;
		this.globalenergyvendor = globalenergyvendor;
		this.globalServiceName = globalServiceName;
		this.ratePerPower = ratePerPower;
	}

	public Globalservices(GlobalservicesId id, Globalenergyvendor globalenergyvendor, String globalServiceName,
			String globalDescription, float ratePerPower, Set<Globalconsumptionlist> globalconsumptionlists) {
		this.id = id;
		this.globalenergyvendor = globalenergyvendor;
		this.globalServiceName = globalServiceName;
		this.globalDescription = globalDescription;
		this.ratePerPower = ratePerPower;
		this.globalconsumptionlists = globalconsumptionlists;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "globalServiceId", column = @Column(name = "GlobalServiceId", nullable = false)),
			@AttributeOverride(name = "globalVendorId", column = @Column(name = "GlobalVendorId", nullable = false)) })
	public GlobalservicesId getId() {
		return this.id;
	}

	public void setId(GlobalservicesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GlobalVendorId", nullable = false, insertable = false, updatable = false)
	public Globalenergyvendor getGlobalenergyvendor() {
		return this.globalenergyvendor;
	}

	public void setGlobalenergyvendor(Globalenergyvendor globalenergyvendor) {
		this.globalenergyvendor = globalenergyvendor;
	}

	@Column(name = "GlobalServiceName", nullable = false, length = 20)
	public String getGlobalServiceName() {
		return this.globalServiceName;
	}

	public void setGlobalServiceName(String globalServiceName) {
		this.globalServiceName = globalServiceName;
	}

	@Column(name = "GlobalDescription", length = 100)
	public String getGlobalDescription() {
		return this.globalDescription;
	}

	public void setGlobalDescription(String globalDescription) {
		this.globalDescription = globalDescription;
	}

	@Column(name = "RatePerPower", nullable = false, precision = 12, scale = 0)
	public float getRatePerPower() {
		return this.ratePerPower;
	}

	public void setRatePerPower(float ratePerPower) {
		this.ratePerPower = ratePerPower;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "globalservices")
	public Set<Globalconsumptionlist> getGlobalconsumptionlists() {
		return this.globalconsumptionlists;
	}

	public void setGlobalconsumptionlists(Set<Globalconsumptionlist> globalconsumptionlists) {
		this.globalconsumptionlists = globalconsumptionlists;
	}

}
