package com.smartenergy.spring.pojo;
// Generated Apr 23, 2016 4:00:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * GlobalconsumptionlistId generated by hbm2java
 */
@Embeddable
public class GlobalconsumptionlistId implements java.io.Serializable {

	private int globalConsumptionListId;
	private int consumerId;
	private int globalServiceId;
	private int globalVendorId;

	public GlobalconsumptionlistId() {
	}

	public GlobalconsumptionlistId(int globalConsumptionListId, int consumerId, int globalServiceId,
			int globalVendorId) {
		this.globalConsumptionListId = globalConsumptionListId;
		this.consumerId = consumerId;
		this.globalServiceId = globalServiceId;
		this.globalVendorId = globalVendorId;
	}

	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "GlobalConsumptionListId", nullable = false)
	public int getGlobalConsumptionListId() {
		return this.globalConsumptionListId;
	}

	public void setGlobalConsumptionListId(int globalConsumptionListId) {
		this.globalConsumptionListId = globalConsumptionListId;
	}

	@Column(name = "ConsumerId", nullable = false)
	public int getConsumerId() {
		return this.consumerId;
	}

	public void setConsumerId(int consumerId) {
		this.consumerId = consumerId;
	}

	@Column(name = "GlobalServiceId", nullable = false)
	public int getGlobalServiceId() {
		return this.globalServiceId;
	}

	public void setGlobalServiceId(int globalServiceId) {
		this.globalServiceId = globalServiceId;
	}

	@Column(name = "GlobalVendorId", nullable = false)
	public int getGlobalVendorId() {
		return this.globalVendorId;
	}

	public void setGlobalVendorId(int globalVendorId) {
		this.globalVendorId = globalVendorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GlobalconsumptionlistId))
			return false;
		GlobalconsumptionlistId castOther = (GlobalconsumptionlistId) other;

		return (this.getGlobalConsumptionListId() == castOther.getGlobalConsumptionListId())
				&& (this.getConsumerId() == castOther.getConsumerId())
				&& (this.getGlobalServiceId() == castOther.getGlobalServiceId())
				&& (this.getGlobalVendorId() == castOther.getGlobalVendorId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGlobalConsumptionListId();
		result = 37 * result + this.getConsumerId();
		result = 37 * result + this.getGlobalServiceId();
		result = 37 * result + this.getGlobalVendorId();
		return result;
	}

}
