package com.smartenergy.spring.pojo;
// Generated Apr 23, 2016 4:00:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * LocalconsumptionlistId generated by hbm2java
 */
@Embeddable
public class LocalconsumptionlistId implements java.io.Serializable {

	private int localConsumptionId;
	private int localServicesId;
	private int localEnergyVendorId;
	private int consumerId;

	public LocalconsumptionlistId() {
	}

	public LocalconsumptionlistId(int localConsumptionId, int localServicesId, int localEnergyVendorId,
			int consumerId) {
		this.localConsumptionId = localConsumptionId;
		this.localServicesId = localServicesId;
		this.localEnergyVendorId = localEnergyVendorId;
		this.consumerId = consumerId;
	}

	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "LocalConsumptionId", nullable = false)
	public int getLocalConsumptionId() {
		return this.localConsumptionId;
	}

	public void setLocalConsumptionId(int localConsumptionId) {
		this.localConsumptionId = localConsumptionId;
	}

	@Column(name = "LocalServicesId", nullable = false)
	public int getLocalServicesId() {
		return this.localServicesId;
	}

	public void setLocalServicesId(int localServicesId) {
		this.localServicesId = localServicesId;
	}

	@Column(name = "LocalEnergyVendorId", nullable = false)
	public int getLocalEnergyVendorId() {
		return this.localEnergyVendorId;
	}

	public void setLocalEnergyVendorId(int localEnergyVendorId) {
		this.localEnergyVendorId = localEnergyVendorId;
	}

	@Column(name = "ConsumerId", nullable = false)
	public int getConsumerId() {
		return this.consumerId;
	}

	public void setConsumerId(int consumerId) {
		this.consumerId = consumerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocalconsumptionlistId))
			return false;
		LocalconsumptionlistId castOther = (LocalconsumptionlistId) other;

		return (this.getLocalConsumptionId() == castOther.getLocalConsumptionId())
				&& (this.getLocalServicesId() == castOther.getLocalServicesId())
				&& (this.getLocalEnergyVendorId() == castOther.getLocalEnergyVendorId())
				&& (this.getConsumerId() == castOther.getConsumerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLocalConsumptionId();
		result = 37 * result + this.getLocalServicesId();
		result = 37 * result + this.getLocalEnergyVendorId();
		result = 37 * result + this.getConsumerId();
		return result;
	}

}
