/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DonorRole;

import Business.Donor.BloodSummary;
import Business.Donor.Donor;
import Business.Donor.DonorHistory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Role.DonorRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neerajsing Rajput
 */
public class ViewDonorHistory extends javax.swing.JPanel {

    JPanel userProcessContanier;
    UserAccount userAccount;
    Organization org;
    Enterprise enterprise;
    EcoSystem eSystem;
    DonorHistory dh;

    /**
     * Creates new form DonorWorkAreaPanel
     */
    public ViewDonorHistory(JPanel pnl, UserAccount ua, Organization o, Enterprise e, EcoSystem es) {
        initComponents();
        userProcessContanier = pnl;
        userAccount = ua;
        enterprise = e;
        org = o;
        eSystem = es;
        dh = new DonorHistory();
        populateTable();
    }

    public void populateTable() {
        ArrayList<Donor> donorHistory = new ArrayList<>();
        if (org instanceof DonorOrganization) {
            DonorOrganization DonorOrg = (DonorOrganization) org;
            for (Role r : DonorOrg.getSupportedRole()) {
                DonorRole dr = (DonorRole) r;
                donorHistory.add(dr.getDonor());
            }
        }
        dh.setDonorHistory(donorHistory);
        String donorName = userAccount.getEmployee().getName();
        DefaultTableModel model = (DefaultTableModel) tblDonorHistoryForDonor.getModel();
        model.setRowCount(0);
        for (Donor d : dh.getDonorHistory()) {
            if (d.getName() != null && (d.getName().equals(donorName))) {
                for (BloodSummary bs : d.getBsh().getBloodSummaryList()) {
                    Object[] row = new Object[4];
                    row[0] = d.getBloodType();
                    row[1] = bs.getBarcode();
                    row[2] = bs.getDonationDate();
                    row[3] = d.getName();
                    model.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDonorHistoryForDonor = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("I am Donor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 51, -1, -1));

        tblDonorHistoryForDonor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "BloodType", "BarCode", "DateTaken", "Donor Name"
            }
        ));
        jScrollPane2.setViewportView(tblDonorHistoryForDonor);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 378, 89));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDonorHistoryForDonor;
    // End of variables declaration//GEN-END:variables
}
