/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Consumer.Consumer;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.GlobalEnergy.ConsumerOrganization;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author neera
 */
public class BusinessAnalysisForMayor extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem system;
    private double sumOfPower;
    private double sumOfVoltage;

    /**
     * Creates new form BusinessAnalysisForMayor
     */
    public BusinessAnalysisForMayor(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateNetworkCombo();
        sumOfPower = 0.0;
        sumOfVoltage = 0.0;

    }

    public void populateNetworkCombo() {

        cmbNetwork.removeAllItems();

        for (Network network : system.getNetworkList()) {
            cmbNetwork.addItem(network);
        }

    }

    public void populateTable(Enterprise e) {

        DefaultTableModel model = (DefaultTableModel) tblOverallPowerConsumd.getModel();

        model.setRowCount(0);
        for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof ConsumerOrganization) {

                for (Employee emp : org.getEmployeeDirectory().getEmployeeList()) {
                    if (emp instanceof Consumer) {

                        Object[] row = new Object[3];
                        row[0] = emp.getName();
                        row[1] = ((Consumer) emp).getSensor().sum_Of_Power_Consumption();
                        row[2] = ((Consumer) emp).getSensor().sum_Of_LocalVoltage();
                        model.addRow(row);

                    }

                }

            }

        }

    }

    private void populateEnterpriseComboBox(Network network) {
        enterpriseJComboBox.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            enterpriseJComboBox.addItem(enterprise);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblOverallPowerConsumd = new javax.swing.JTable();
        btnSelect = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbNetwork = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        enterpriseJComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnAvergareConsumerPower = new javax.swing.JButton();
        avgConsumerVoltage = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOverallPowerConsumd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Consumer", "Overall Power Consumed", "Overall Voltage consumed"
            }
        ));
        jScrollPane2.setViewportView(tblOverallPowerConsumd);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 595, 354));

        btnSelect.setText("Show The Table");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel1.setText("Network");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 76, -1, -1));

        cmbNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNetworkActionPerformed(evt);
            }
        });
        add(cmbNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 72, 137, -1));

        jLabel2.setText("Enterprise");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 132, -1, -1));

        enterpriseJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJComboBoxActionPerformed(evt);
            }
        });
        add(enterpriseJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 128, 137, -1));

        jButton1.setText("Get Sum Of consumed power");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 72, 255, -1));

        jButton2.setText("Get Sum of volatage consumed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 128, -1, -1));

        btnAvergareConsumerPower.setText("Get Average Consumer power");
        btnAvergareConsumerPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvergareConsumerPowerActionPerformed(evt);
            }
        });
        add(btnAvergareConsumerPower, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 263, -1));

        avgConsumerVoltage.setText("Get Average Consumer voltage");
        avgConsumerVoltage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgConsumerVoltageActionPerformed(evt);
            }
        });
        add(avgConsumerVoltage, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 130, 270, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Business Analysis for Mayor");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 16, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Table of Consumer Power and Voltage");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNetworkActionPerformed
        // TODO add your handling code here:
        Network network = (Network) cmbNetwork.getSelectedItem();
        if (network != null) {
            populateEnterpriseComboBox(network);
        }


    }//GEN-LAST:event_cmbNetworkActionPerformed

    private void enterpriseJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJComboBoxActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_enterpriseJComboBoxActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        try {
            Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
            populateTable(enterprise);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No enterprise created");
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double sum = 0.0;
        try {
            Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
            sum = system.sumOfAllConsumerPower(enterprise);
            JOptionPane.showMessageDialog(null, "Sum of All the power consumption is" + sum);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No enterprise created");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double sum = 0.0;
        try {
            Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
            sum = system.sumOfAllConsumerVoltage(enterprise);
            JOptionPane.showMessageDialog(null, "Sum of All the Voltage consumption is" + sum);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No enterprise created");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAvergareConsumerPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvergareConsumerPowerActionPerformed
        // TODO add your handling code here:
        double avg = 0.0;
        try {
            Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
            avg = system.avgOfAllConsumerPower(enterprise);
            JOptionPane.showMessageDialog(null, "Avg of All the Power consumption is" + avg);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No enterprise created");
        }
    }//GEN-LAST:event_btnAvergareConsumerPowerActionPerformed

    private void avgConsumerVoltageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgConsumerVoltageActionPerformed
        // TODO add your handling code here:
        double avg = 0.0;
        try {
            Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
            avg = system.avgOfAllConsumerVoltage(enterprise);
            JOptionPane.showMessageDialog(null, "Avg of All the Power consumption is" + avg);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No enterprise created");
        }
    }//GEN-LAST:event_avgConsumerVoltageActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avgConsumerVoltage;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAvergareConsumerPower;
    private javax.swing.JButton btnSelect;
    private javax.swing.JComboBox cmbNetwork;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOverallPowerConsumd;
    // End of variables declaration//GEN-END:variables
}
