/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GlobalManagerRole;

import Business.Employee.Consumer.Consumer;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.GlobalEnergy.ConsumerOrganization;
import Business.Organization.GlobalEnergy.GlobalManagerOrganization;
import Business.Organization.Organization;
import Business.Role.ConsumerRole.ConsumerRole;

import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.Utils.MyStringVerifier;
import Business.WorkQueue.GlobalManagerToLocalManager.SetConsumerWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author neera
 */
public class GlobalManagerAddConsumer extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private GlobalManagerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem busines;
    private Consumer consumer;
    private Boolean checkAddress;
    private UserAccount consumerUserAccount;
    SetConsumerWorkRequest request;

    /**
     * Creates new form GlobalManagerAddConsumer
     */
    public GlobalManagerAddConsumer(JPanel userProcessContainer, UserAccount account, GlobalManagerOrganization organization, Enterprise enterprise, EcoSystem busines, Consumer consumer, SetConsumerWorkRequest request) {

        //valueLabel.setText(enterprise.getName());
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.busines = busines;
        this.consumer = consumer;
        this.request = request;
        checkAddress = false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAddress = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSetUserAccount = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaAddress.setColumns(20);
        txtAreaAddress.setRows(5);
        jScrollPane1.setViewportView(txtAreaAddress);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 182, 230, -1));

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 143, -1, -1));

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 140, 230, -1));

        jLabel5.setText("Address:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 182, -1, -1));

        btnSetUserAccount.setText("Set User Account");
        btnSetUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetUserAccountActionPerformed(evt);
            }
        });
        add(btnSetUserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 387, -1, -1));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 287, 230, -1));

        jLabel3.setText("User Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 290, -1, -1));

        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 334, -1, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 230, -1));

        btnBack.setText("<<back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 387, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Add Consumer to the System");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 42, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetUserAccountActionPerformed
        // TODO add your handling code here:
        MyStringVerifier stringVerify = new MyStringVerifier();
        Role r = new ConsumerRole();
        if (stringVerify.verify(txtName) && stringVerify.verify(txtUserName));
        {
            String name = txtName.getText();
            String address = txtAreaAddress.getText();
            String userName = txtUserName.getText();

            char[] passwordCharArray = txtPassword.getPassword();
            String password = String.valueOf(passwordCharArray);
            if (address.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Addess is must have field");
                return;
            }
            consumer.setAddress(address);
            consumer.setName(name);

            for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof ConsumerOrganization) {
                    if (!checkAdress(address) && busines.checkIfUsernameIsUnique(userName)) {
                        consumer.setAddress(address);
                        Business.Employee.Consumer.Consumer employee = org.getEmployeeDirectory().createConsumer(name, address);
                        UserAccount consumerUserAccount = org.getUserAccountDirectory().createUserAccount(userName, password, employee, r);

                        JOptionPane.showMessageDialog(null, "User account created");
                        break;
                    } else {
                        JOptionPane.showMessageDialog(null, "Cannot have same address or User Name match");
                        break;
                    }
                }
            }
            //Creating a new role For Consumer
        }


    }//GEN-LAST:event_btnSetUserAccountActionPerformed

    public boolean checkAdress(String address) {
        boolean flag = false;
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof ConsumerOrganization) {
                //Adding Consumer to the Employee Directory
                for (Employee emp : org.getEmployeeDirectory().getEmployeeList()) {
                    //org.getEmployeeDirectory().createConsumer(name, address);
                    //Creating Consumer Account
                    if (emp instanceof Consumer) {
                        if (address.equals(((Consumer) emp).getAddress())) {
                            flag = true;
                        } else {
                            flag = false;
                        }
                    }
                }
            }
        }
        return flag;
    }

    //Limit name to 20
    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        if (txtName.getText().length() >= 20) {
            txtName.setText(txtName.getText().substring(0, 19));
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        GlobalManagerWorkAreaJPanel dwjp = (GlobalManagerWorkAreaJPanel) component;
        dwjp.populateConsumerTable();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSetUserAccount;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
