/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BillingOrganization;

import Business.EcoSystem;
import Business.Employee.Consumer.Consumer;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GlobalEnterprise.GlobalEnterprise;
import Business.Organization.GlobalEnergy.ConsumerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Billing.BillValueToConsumer;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author neera
 */
public class BillingWorkAreaPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    EcoSystem business;
    double amount;
    int consumption;

    /**
     * Creates new form BillingWorkAreaPanel
     */
    public BillingWorkAreaPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        amount = 0.0;
        consumption = 0;
        populateComboBox();

    }

    public void populateComboBox() {
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof ConsumerOrganization) {
                for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {

                    cmbConsumer.addItem(ua);

                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbConsumer = new javax.swing.JComboBox();
        btnConsumption = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEnergyConsumption = new javax.swing.JLabel();
        lblBillAmount = new javax.swing.JLabel();
        btnSendBillToConsumer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Billing Organization");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel2.setText("Consumer UserAccount");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        cmbConsumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConsumerActionPerformed(evt);
            }
        });
        add(cmbConsumer, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 103, 265, -1));

        btnConsumption.setText("View Consumption and Charges");
        btnConsumption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsumptionActionPerformed(evt);
            }
        });
        add(btnConsumption, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 178, -1, -1));

        jLabel3.setText("Energy Consumption");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 250, -1, -1));

        jLabel4.setText("Charge applied");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 304, -1, -1));

        lblEnergyConsumption.setText("<value>");
        add(lblEnergyConsumption, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 250, -1, -1));

        lblBillAmount.setText("<value>");
        add(lblBillAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 304, -1, -1));

        btnSendBillToConsumer.setText("Send Bill to Consumer");
        btnSendBillToConsumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendBillToConsumerActionPerformed(evt);
            }
        });
        add(btnSendBillToConsumer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        jLabel5.setText("KWatts");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jLabel6.setText("$");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsumptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsumptionActionPerformed
        // TODO add your handling code here:
        UserAccount ua = (UserAccount) cmbConsumer.getSelectedItem();
        if (enterprise instanceof GlobalEnterprise) {
            if (ua.getEmployee() instanceof Consumer) {
                Consumer consumer = (Consumer) ua.getEmployee();
                GlobalEnterprise ge = (GlobalEnterprise) enterprise;
                amount = ge.generateConsumerMonthlyBill(consumer);
                consumption = ge.calculateEnergyOfCurrentMonth(consumer.getSensor());
                lblEnergyConsumption.setText(String.valueOf(consumption));
                lblBillAmount.setText(String.valueOf(amount));
            }
        }
    }//GEN-LAST:event_btnConsumptionActionPerformed

    private void cmbConsumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConsumerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbConsumerActionPerformed

    private void btnSendBillToConsumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendBillToConsumerActionPerformed
        // TODO add your handling code here:
        UserAccount ua = (UserAccount) cmbConsumer.getSelectedItem();
        if (amount != 0.0) {
            BillValueToConsumer request = new BillValueToConsumer();
            request.setBillValue(amount);
            request.setConsumptionValue(consumption);
            ua.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "The consumer bill is sent");
        } else {
            JOptionPane.showMessageDialog(null, "You cannot charge 0 bill amount to Consumer");
        }

    }//GEN-LAST:event_btnSendBillToConsumerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsumption;
    private javax.swing.JButton btnSendBillToConsumer;
    private javax.swing.JComboBox cmbConsumer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBillAmount;
    private javax.swing.JLabel lblEnergyConsumption;
    // End of variables declaration//GEN-END:variables
}
