/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReciptionistRole;

import userinterface.DonorRole.*;
import Business.Donor.BloodSummary;
import Business.Donor.Donor;
import Business.Donor.DonorHistory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Role.DonorRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.NurseRole.NurseWorkAreaPanel;

/**
 *
 * @author Neerajsing Rajput
 */
public class ViewDonorHistory extends javax.swing.JPanel {

    JPanel userProcessContanier;

    Organization org;

    DonorHistory dh;

    /**
     * Creates new form DonorWorkAreaPanel
     */
    public ViewDonorHistory(JPanel pnl, Organization o) {
        initComponents();
        userProcessContanier = pnl;
        org = o;
        dh = new DonorHistory();
        populateTable();
    }

    public void populateTable() {

        DefaultTableModel model2 = (DefaultTableModel) tblDonorHistory.getModel();
        ArrayList<Donor> donorHistory = new ArrayList<>();

        model2.setRowCount(0);
        if (org instanceof DonorOrganization) {
            DonorOrganization DonorOrg = (DonorOrganization) org;
            for (Role r : DonorOrg.getSupportedRole()) {
                DonorRole dr = (DonorRole) r;
                if (dr.getDonor().getBsh().getBloodSummaryList() != null) {
                    for (BloodSummary bs : dr.getDonor().getBsh().getBloodSummaryList()) {
                        Object[] row = new Object[4];
                        row[0] = dr.getDonor().getBloodType();
                        row[1] = bs.getBarcode();
                        row[2] = bs.getDonationDate();
                        row[3] = dr.getDonor().getName();
                        model2.addRow(row);
                    }
                }
                donorHistory.add(dr.getDonor());
            }
        }
        dh.setDonorHistory(donorHistory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDonorHistoryForDonor = new javax.swing.JTable();
        txtDonorName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDonorHistory = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("I am Donor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 51, -1, -1));

        tblDonorHistoryForDonor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "BloodType", "BarCode", "DateTaken", "Donor Name"
            }
        ));
        jScrollPane2.setViewportView(tblDonorHistoryForDonor);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 378, 89));
        add(txtDonorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 80, -1));

        jButton2.setText("Search by Name");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        tblDonorHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "BloodType", "BarCode", "DateTaken", "Donor Name"
            }
        ));
        jScrollPane3.setViewportView(tblDonorHistory);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 378, 89));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String donorName = txtDonorName.getText();
        DefaultTableModel model = (DefaultTableModel) tblDonorHistoryForDonor.getModel();
        model.setRowCount(0);
        for (Donor d : dh.getDonorHistory()) {
            if (d.getName() != null && d.getName().contains(donorName)) {
                for (BloodSummary bs : d.getBsh().getBloodSummaryList()) {
                    Object[] row = new Object[4];
                    row[0] = d.getBloodType();
                    row[1] = bs.getBarcode();
                    row[2] = bs.getDonationDate();
                    row[3] = d.getName();
                    model.addRow(row);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContanier.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContanier.getLayout();
        cardLayout.previous(userProcessContanier);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblDonorHistory;
    private javax.swing.JTable tblDonorHistoryForDonor;
    private javax.swing.JTextField txtDonorName;
    // End of variables declaration//GEN-END:variables
}
