/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GlobalMaintainenceRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.GlobalEnergy.GlobalMaintainenceOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ConsumerRequests.RequestToGlobalMaintainence;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neerajsing Rajput
 */
public class GlobalMaintainenceWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    /**
     * Creates new form GlobalMaintainenceWorkAreaJPanel
     */
    public GlobalMaintainenceWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = (GlobalMaintainenceOrganization) organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;

        populateRequestTable();
    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof RequestToGlobalMaintainence) {
                Object[] row = new Object[4];
                row[0] = request;
                row[1] = request.getReceiver();
                row[2] = request.getStatus();

                //String result = request.getTestResult();
                row[3] = request.getSender();

                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        txtMessage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AssignToMeBtn = new javax.swing.JButton();
        msgButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Receiver", "Status", "Sender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 60, 1060, 170));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 270, 236, -1));

        jLabel3.setText("Type your Message");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 270, -1, -1));

        AssignToMeBtn.setText("Assign me");
        AssignToMeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignToMeBtnActionPerformed(evt);
            }
        });
        add(AssignToMeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 280, -1, -1));

        msgButton.setText("Send back to consumer");
        msgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgButtonActionPerformed(evt);
            }
        });
        add(msgButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Request from Consumer");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AssignToMeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignToMeBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {

            return;
        }
        RequestToGlobalMaintainence request = (RequestToGlobalMaintainence) workRequestJTable.getValueAt(selectedRow, 0);

        request.setReceiver(userAccount);
       
        populateRequestTable();
    }//GEN-LAST:event_AssignToMeBtnActionPerformed

    private void msgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }
        RequestToGlobalMaintainence request = (RequestToGlobalMaintainence) workRequestJTable.getValueAt(selectedRow, 0);
        request.setMessage(txtMessage.getText());
        request.setStatus("Complete");
        request.setReceiver(userAccount);
        populateRequestTable();
        JOptionPane.showMessageDialog(null, "Sent to Consumer");
    }//GEN-LAST:event_msgButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignToMeBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton msgButton;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
