/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LocalMaintainenceRole;

import Business.EcoSystem;
import Business.Employee.Consumer.ConsumerBattery;
import Business.Employee.Consumer.Sensor;
import Business.Enterprise.Enterprise;
import Business.LocalEnergy.CommunitySensor;
import Business.Organization.LocalEnergy.LocalAreaEnergyMaintainenceOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ConsumerRequests.RequestToLocalMaintainence;
import Business.WorkQueue.WorkRequest;
import java.util.Date;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author neera
 */
public class LocalMaintainenceWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    /**
     * Creates new form LocalMaintainenceWorkAreaJPanel
     */
    public LocalMaintainenceWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = (LocalAreaEnergyMaintainenceOrganization) organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        
        populateRequestTable();
        
    }
    
    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof RequestToLocalMaintainence) {
                Object[] row = new Object[5];
                row[0] = request;
                row[1] = request.getReceiver();
                row[2] = request.getStatus();

                //String result = request.getTestResult();
                row[3] = request.getSender();
                row[4] = ((RequestToLocalMaintainence) request).getSensor();
                
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtMessage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AssignToMeBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        localConsumptionTable = new javax.swing.JTable();
        btnSensordata = new javax.swing.JButton();
        msgButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Receiver", "Status", "Sender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 90, 1060, 170));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Request from Consumer");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        btnSubmit.setText("Charge Battery to Maximum");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 250, -1));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 300, 236, -1));

        jLabel3.setText("Type your Message");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, -1, -1));

        AssignToMeBtn.setText("Assign me");
        AssignToMeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignToMeBtnActionPerformed(evt);
            }
        });
        add(AssignToMeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        localConsumptionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Timestamp", "Device Consumption"
            }
        ));
        jScrollPane3.setViewportView(localConsumptionTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 1050, -1));

        btnSensordata.setText("Mandatory Check Sensor data");
        btnSensordata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSensordataActionPerformed(evt);
            }
        });
        add(btnSensordata, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        msgButton.setText("Send back to consumer");
        msgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgButtonActionPerformed(evt);
            }
        });
        add(msgButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0) {
            return;
        }
        RequestToLocalMaintainence request = (RequestToLocalMaintainence) workRequestJTable.getValueAt(selectedRow, 0);
        ConsumerBattery conBattery = new ConsumerBattery();
        conBattery.setBatteryVolts(CommunitySensor.MAX_VOLTAGE);
        request.getSensor().setBattery(conBattery);
        JOptionPane.showMessageDialog(null, "Consumer Battery Set to Max Voltage!");
    }//GEN-LAST:event_btnSubmitActionPerformed
    

    private void AssignToMeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignToMeBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0) {
            
            return;
        }
        RequestToLocalMaintainence request = (RequestToLocalMaintainence) workRequestJTable.getValueAt(selectedRow, 0);
        
        request.setReceiver(userAccount);
        populateRequestTable();
    }//GEN-LAST:event_AssignToMeBtnActionPerformed

    private void btnSensordataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSensordataActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0) {
            
            return;
        }
        RequestToLocalMaintainence request = (RequestToLocalMaintainence) workRequestJTable.getValueAt(selectedRow, 0);
        
        populateLocalConsumptionData(request.getSensor());

    }//GEN-LAST:event_btnSensordataActionPerformed

    private void msgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0) {
            return;
        }
        RequestToLocalMaintainence request = (RequestToLocalMaintainence) workRequestJTable.getValueAt(selectedRow, 0);
        request.setMessage(txtMessage.getText());
        request.setStatus("Complete");
        request.setReceiver(userAccount);
        
        JOptionPane.showMessageDialog(null, "Sent to Consumer");
    }//GEN-LAST:event_msgButtonActionPerformed
    
    public void populateLocalConsumptionData(Sensor s) {
        DefaultTableModel model = (DefaultTableModel) localConsumptionTable.getModel();
        
        model.setRowCount(0);
        for (Map.Entry<Date, Integer> entry : s.getGlobalConsumptionList().entrySet()) {
            Object[] row = new Object[2];
            row[0] = entry.getKey();
            row[1] = entry.getValue();
            model.addRow(row);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignToMeBtn;
    private javax.swing.JButton btnSensordata;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable localConsumptionTable;
    private javax.swing.JButton msgButton;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
