/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Patient;
import Business.PatientDirectory;
import Business.Person;
import Business.PersonDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Neerajsing Rajput
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    PersonDirectory personDirectory;
    Person person;
    PatientDirectory patientDierectory;

    public MainJFrame() {
        personDirectory = new PersonDirectory();
        person = new Person();
        patientDierectory = new PatientDirectory();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnCreatePerson = new javax.swing.JButton();
        btnManagePatientProfile = new javax.swing.JButton();
        btnReporting = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 620));

        btnCreatePerson.setText("Manage Person Profile");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnManagePatientProfile.setText("Manage Patient Profile");
        btnManagePatientProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePatientProfileActionPerformed(evt);
            }
        });

        btnReporting.setText("Reporting");
        btnReporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreatePerson)
                    .addComponent(btnManagePatientProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReporting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnCreatePerson)
                .addGap(36, 36, 36)
                .addComponent(btnManagePatientProfile)
                .addGap(27, 27, 27)
                .addComponent(btnReporting)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
        PersonWorkAreaPanel panel = new PersonWorkAreaPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("PersonWorkAreaPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnManagePatientProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePatientProfileActionPerformed
        // TODO add your handling code here:

        if (!personDirectory.getPersonList().isEmpty()) {
            //Get person from PersonDirectory and then pass it in PatientJPanel
            ArrayList<String> getNameOfPerson = new ArrayList<>();
            for (int i = 0; i < personDirectory.getPersonList().size(); i++) {
                Person p = personDirectory.getPersonList().get(i);
                getNameOfPerson.add(p.getPersonName());
            }
            Object[] selectedPersonOption = getNameOfPerson.toArray();
            String selectedPerson = (String) JOptionPane.showInputDialog(null, "Please select the person name whose patient information has to be filled or updated\n", "Options", JOptionPane.PLAIN_MESSAGE, null, selectedPersonOption, "");
            if (selectedPerson != null && !selectedPerson.isEmpty()) {
                Person p = personDirectory.searchPerson(selectedPerson);
                CreatePatientJPanel panel = new CreatePatientJPanel(userProcessContainer, p, personDirectory);
                userProcessContainer.add("CreatePatientJPanel", panel);
                CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
                cardLayout.next(userProcessContainer);
            } else {
                JOptionPane.showMessageDialog(null, "The person has to be linked to the patient so you have to select person");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Person is not created so create him", "Infomation", JOptionPane.INFORMATION_MESSAGE);
            CreatePersonJPanel panel = new CreatePersonJPanel(userProcessContainer, personDirectory);
            userProcessContainer.add("CreatePersonJPanel", panel);
            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnManagePatientProfileActionPerformed

    private void btnReportingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportingActionPerformed
        // TODO add your handling code here:
        ArrayList<Patient> patientList = new ArrayList<>();
        for (Person p : personDirectory.getPersonList()) {
            Patient patient = p.getPatient();
            patientList.add(patient);
        }

        patientDierectory.setPatientList(patientList);
        //personDirectory.getPersonList()
        ManagePatientJPanel panel = new ManagePatientJPanel(userProcessContainer, patientDierectory, personDirectory);
        userProcessContainer.add("ManagePatientJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnReportingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JButton btnManagePatientProfile;
    private javax.swing.JButton btnReporting;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
