/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.PersonDirectory;
import Business.VitalSign;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Neerajsing Rajput
 */
public class ViewVitalSignJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    VitalSign vitalsign;

    /**
     * Creates new form ViewVitalSignJPanel
     */
    public ViewVitalSignJPanel(JPanel upc, VitalSign vs) {
        initComponents();
        userProcessContainer = upc;
        vitalsign = vs;
        populateForm();
        setComponentsEnabled(false);
        btnSave.setEnabled(false);
        
    }

    public void setComponentsEnabled(boolean isEnabled) {
        txtBloodPressure.setEnabled(isEnabled);
        txtHeartRate.setEnabled(isEnabled);
        txtRespiratoryRate.setEnabled(isEnabled);
        txtWeights.setEnabled(isEnabled);
    }

    public void populateForm() {
        txtBloodPressure.setText(String.valueOf(vitalsign.getBloodPressure()));
        txtHeartRate.setText(String.valueOf(vitalsign.getHeartRate()));
        txtRespiratoryRate.setText(String.valueOf(vitalsign.getRespiratoryRate()));
        txtWeights.setText(String.valueOf(vitalsign.getWeightInPounds()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtHeartRate = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtWeights = new javax.swing.JTextField();
        txtRespiratoryRate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Blood Pressure");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 141, -1, -1));

        jLabel10.setText("Weight(lbs)");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 179, -1, -1));
        add(txtHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 100, 192, -1));
        add(txtBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 138, 192, -1));

        jLabel6.setText("Respiratory Rate");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 65, -1, -1));
        add(txtWeights, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 176, 192, -1));
        add(txtRespiratoryRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 62, 192, -1));

        jLabel8.setText("Heart Rate");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 103, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 224, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 224, -1, -1));

        btnBack.setText("<<back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 265, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("View VitalSigns");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 24, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        //This helps layout manager pointing to the next layout
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        setComponentsEnabled(true);
        btnSave.setEnabled(true);
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        int respiratoryrate =-1; 
        int heartRate=-1;
        int bloodPressure = -1;
        int weights=-1;
        try {
            respiratoryrate=Integer.parseInt(txtRespiratoryRate.getText());
            heartRate=Integer.parseInt(txtHeartRate.getText());
            bloodPressure = Integer.parseInt(txtBloodPressure.getText());
            weights=Integer.parseInt(txtWeights.getText());
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter return value ");
            return;
        }
        vitalsign.setHeartRate(heartRate);
        vitalsign.setBloodPressure(bloodPressure);
        vitalsign.setRespiratoryRate(respiratoryrate);
        vitalsign.setWeightInPounds(weights);
       
        JOptionPane.showMessageDialog(null, "Vital sign information updated Successfully!!!");
    }//GEN-LAST:event_btnSaveActionPerformed

    public void refreshTable() {
        int index = userProcessContainer.getComponentCount() - 1;
        SearchResultJPanel panel = (SearchResultJPanel) userProcessContainer.getComponent(index);
        panel.populateTable();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtRespiratoryRate;
    private javax.swing.JTextField txtWeights;
    // End of variables declaration//GEN-END:variables
}
