/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole.LocalEnterprise;

import Business.Organization.LocalEnergy.LocalAreaOrganization;
import Business.Organization.Organization;

import Business.Organization.Organization.LocalOrganizationType;
import Business.Organization.OrganizationDirectory;
import Business.Utils.MyIntegerVerifier;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class LocalMngOrganizationJPanel extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    private Boolean isCodeMatch;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public LocalMngOrganizationJPanel(JPanel userProcessContainer, OrganizationDirectory directory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = directory;
        isCodeMatch = false;
        populateTable();
        populateCombo();
    }

    private void populateCombo() {
        organizationJComboBox.removeAllItems();
        for (Organization.LocalOrganizationType type : Organization.LocalOrganizationType.values()) {
            if (!type.getValue().equals(LocalOrganizationType.Admin.getValue())) {
                organizationJComboBox.addItem(type);
            }
        }
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();

        model.setRowCount(0);

        for (Organization organization : directory.getOrganizationList()) {
            if (organization instanceof LocalAreaOrganization) {
                LocalAreaOrganization locOrg = (LocalAreaOrganization) organization;
                Object[] row = new Object[2];

                row[0] = organization.getName();
                row[1] = locOrg.getLocalAreaCode();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        addJButton = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtLocalOrgCode = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Local Area Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 60, 480, 92));

        addJButton.setText("Add Organization");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 314, -1, -1));

        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 170, 240, -1));

        jLabel1.setText("Organization Type ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 173, -1, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 314, -1, -1));

        jLabel2.setText("Local Organization Code");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 217, -1, -1));
        add(txtLocalOrgCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 214, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

        int code = 0;
        LocalOrganizationType type = (LocalOrganizationType) organizationJComboBox.getSelectedItem();
        MyIntegerVerifier intVerify = new MyIntegerVerifier();
        if (intVerify.verify(txtLocalOrgCode)) {
            //Now check for the Uniqueness of cade
            code = Integer.parseInt(txtLocalOrgCode.getText());
            for (Organization organization : directory.getOrganizationList()) {
                if (organization instanceof LocalAreaOrganization) {
                    if (((LocalAreaOrganization) organization).getLocalAreaCode() == code) {
                        isCodeMatch = true;
                        JOptionPane.showMessageDialog(null, "You cannot add same code for local area");
                    } else {
                        isCodeMatch = false;
                    }
                }
            }
            if (!isCodeMatch) {
                directory.createLocalOrganization(type, code);
                populateTable();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Some wrong data entered!");
        }
        //Check for Uniqueness of Code


    }//GEN-LAST:event_addJButtonActionPerformed


    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTable organizationJTable;
    private javax.swing.JTextField txtLocalOrgCode;
    // End of variables declaration//GEN-END:variables
}
