package com.smartenergy.spring.pojo.hib1;
// Generated Apr 17, 2016 9:30:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Billingtype generated by hbm2java
 */
@Entity
@Table(name = "billingtype", catalog = "smartenergy2")
public class Billingtype implements java.io.Serializable {

	private Integer billingTypeId;
	private int year;
	private String month;
	private Set<Consumerservicesbilling> consumerservicesbillings = new HashSet<Consumerservicesbilling>(0);

	public Billingtype() {
	}

	public Billingtype(int year, String month) {
		this.year = year;
		this.month = month;
	}

	public Billingtype(int year, String month, Set<Consumerservicesbilling> consumerservicesbillings) {
		this.year = year;
		this.month = month;
		this.consumerservicesbillings = consumerservicesbillings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BillingTypeId", unique = true, nullable = false)
	public Integer getBillingTypeId() {
		return this.billingTypeId;
	}

	public void setBillingTypeId(Integer billingTypeId) {
		this.billingTypeId = billingTypeId;
	}

	@Column(name = "Year", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "Month", nullable = false, length = 20)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "billingtype")
	public Set<Consumerservicesbilling> getConsumerservicesbillings() {
		return this.consumerservicesbillings;
	}

	public void setConsumerservicesbillings(Set<Consumerservicesbilling> consumerservicesbillings) {
		this.consumerservicesbillings = consumerservicesbillings;
	}

}
