package com.smartenergy.spring.pojo.hib1;
// Generated Apr 17, 2016 9:30:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Consumerservicesbilling generated by hbm2java
 */
@Entity
@Table(name = "consumerservicesbilling", catalog = "smartenergy2")
public class Consumerservicesbilling implements java.io.Serializable {

	private ConsumerservicesbillingId id;
	private Consumer consumer;
	private Billingtype billingtype;
	private float localMonthlyEnergyBill;
	private float globalMonthlyEnergyBill;

	public Consumerservicesbilling() {
	}

	public Consumerservicesbilling(ConsumerservicesbillingId id, Consumer consumer, Billingtype billingtype,
			float localMonthlyEnergyBill, float globalMonthlyEnergyBill) {
		this.id = id;
		this.consumer = consumer;
		this.billingtype = billingtype;
		this.localMonthlyEnergyBill = localMonthlyEnergyBill;
		this.globalMonthlyEnergyBill = globalMonthlyEnergyBill;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "consumerServicesId", column = @Column(name = "ConsumerServicesId", nullable = false)),
			@AttributeOverride(name = "billingTypeId", column = @Column(name = "BillingTypeId", nullable = false)),
			@AttributeOverride(name = "consumerId", column = @Column(name = "ConsumerId", nullable = false)) })
	public ConsumerservicesbillingId getId() {
		return this.id;
	}

	public void setId(ConsumerservicesbillingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ConsumerId", nullable = false, insertable = false, updatable = false)
	public Consumer getConsumer() {
		return this.consumer;
	}

	public void setConsumer(Consumer consumer) {
		this.consumer = consumer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BillingTypeId", nullable = false, insertable = false, updatable = false)
	public Billingtype getBillingtype() {
		return this.billingtype;
	}

	public void setBillingtype(Billingtype billingtype) {
		this.billingtype = billingtype;
	}

	@Column(name = "LocalMonthlyEnergyBill", nullable = false, precision = 12, scale = 0)
	public float getLocalMonthlyEnergyBill() {
		return this.localMonthlyEnergyBill;
	}

	public void setLocalMonthlyEnergyBill(float localMonthlyEnergyBill) {
		this.localMonthlyEnergyBill = localMonthlyEnergyBill;
	}

	@Column(name = "GlobalMonthlyEnergyBill", nullable = false, precision = 12, scale = 0)
	public float getGlobalMonthlyEnergyBill() {
		return this.globalMonthlyEnergyBill;
	}

	public void setGlobalMonthlyEnergyBill(float globalMonthlyEnergyBill) {
		this.globalMonthlyEnergyBill = globalMonthlyEnergyBill;
	}

}
