package com.smartenergy.spring.pojo.hib1;
// Generated Apr 17, 2016 9:30:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GlobalservicesId generated by hbm2java
 */
@Embeddable
public class GlobalservicesId implements java.io.Serializable {

	private int globalServiceId;
	private int globalVendorId;

	public GlobalservicesId() {
	}

	public GlobalservicesId(int globalServiceId, int globalVendorId) {
		this.globalServiceId = globalServiceId;
		this.globalVendorId = globalVendorId;
	}

	@Column(name = "GlobalServiceId", nullable = false)
	public int getGlobalServiceId() {
		return this.globalServiceId;
	}

	public void setGlobalServiceId(int globalServiceId) {
		this.globalServiceId = globalServiceId;
	}

	@Column(name = "GlobalVendorId", nullable = false)
	public int getGlobalVendorId() {
		return this.globalVendorId;
	}

	public void setGlobalVendorId(int globalVendorId) {
		this.globalVendorId = globalVendorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GlobalservicesId))
			return false;
		GlobalservicesId castOther = (GlobalservicesId) other;

		return (this.getGlobalServiceId() == castOther.getGlobalServiceId())
				&& (this.getGlobalVendorId() == castOther.getGlobalVendorId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGlobalServiceId();
		result = 37 * result + this.getGlobalVendorId();
		return result;
	}

}
