package com.smartenergy.spring.pojo.hib1;
// Generated Apr 17, 2016 9:30:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Localenergyservices generated by hbm2java
 */
@Entity
@Table(name = "localenergyservices", catalog = "smartenergy2", uniqueConstraints = @UniqueConstraint(columnNames = "LocalEnergyServiceName"))
public class Localenergyservices implements java.io.Serializable {

	private LocalenergyservicesId id;
	private Localenergyvendor localenergyvendor;
	private String localEnergyServiceName;
	private String localEnergyServiceDescription;
	private String rate;
	private String zip;
	private Set<Localconsumptionlist> localconsumptionlists = new HashSet<Localconsumptionlist>(0);

	public Localenergyservices() {
	}

	public Localenergyservices(LocalenergyservicesId id, Localenergyvendor localenergyvendor,
			String localEnergyServiceName, String rate, String zip) {
		this.id = id;
		this.localenergyvendor = localenergyvendor;
		this.localEnergyServiceName = localEnergyServiceName;
		this.rate = rate;
		this.zip = zip;
	}

	public Localenergyservices(LocalenergyservicesId id, Localenergyvendor localenergyvendor,
			String localEnergyServiceName, String localEnergyServiceDescription, String rate, String zip,
			Set<Localconsumptionlist> localconsumptionlists) {
		this.id = id;
		this.localenergyvendor = localenergyvendor;
		this.localEnergyServiceName = localEnergyServiceName;
		this.localEnergyServiceDescription = localEnergyServiceDescription;
		this.rate = rate;
		this.zip = zip;
		this.localconsumptionlists = localconsumptionlists;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "localServicesId", column = @Column(name = "LocalServicesId", nullable = false)),
			@AttributeOverride(name = "localEnergyVendorId", column = @Column(name = "LocalEnergyVendorId", nullable = false)) })
	public LocalenergyservicesId getId() {
		return this.id;
	}

	public void setId(LocalenergyservicesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LocalEnergyVendorId", nullable = false, insertable = false, updatable = false)
	public Localenergyvendor getLocalenergyvendor() {
		return this.localenergyvendor;
	}

	public void setLocalenergyvendor(Localenergyvendor localenergyvendor) {
		this.localenergyvendor = localenergyvendor;
	}

	@Column(name = "LocalEnergyServiceName", unique = true, nullable = false, length = 20)
	public String getLocalEnergyServiceName() {
		return this.localEnergyServiceName;
	}

	public void setLocalEnergyServiceName(String localEnergyServiceName) {
		this.localEnergyServiceName = localEnergyServiceName;
	}

	@Column(name = "LocalEnergyServiceDescription", length = 100)
	public String getLocalEnergyServiceDescription() {
		return this.localEnergyServiceDescription;
	}

	public void setLocalEnergyServiceDescription(String localEnergyServiceDescription) {
		this.localEnergyServiceDescription = localEnergyServiceDescription;
	}

	@Column(name = "Rate", nullable = false, length = 20)
	public String getRate() {
		return this.rate;
	}

	public void setRate(String rate) {
		this.rate = rate;
	}

	@Column(name = "Zip", nullable = false, length = 5)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localenergyservices")
	public Set<Localconsumptionlist> getLocalconsumptionlists() {
		return this.localconsumptionlists;
	}

	public void setLocalconsumptionlists(Set<Localconsumptionlist> localconsumptionlists) {
		this.localconsumptionlists = localconsumptionlists;
	}

}
