package com.smartenergy.spring.pojo.hib1;
// Generated Apr 17, 2016 9:30:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Localenergyvendor generated by hbm2java
 */
@Entity
@Table(name = "localenergyvendor", catalog = "smartenergy2")
public class Localenergyvendor implements java.io.Serializable {

	private Integer localEnergyVendorId;
	private Useraccount useraccount;
	private String localEnergyVendorName;
	private String localEnergyVendorDescription;
	private String zip;
	private Set<Localenergyservices> localenergyserviceses = new HashSet<Localenergyservices>(0);

	public Localenergyvendor() {
	}

	public Localenergyvendor(String localEnergyVendorName, String zip) {
		this.localEnergyVendorName = localEnergyVendorName;
		this.zip = zip;
	}

	public Localenergyvendor(Useraccount useraccount, String localEnergyVendorName, String localEnergyVendorDescription,
			String zip, Set<Localenergyservices> localenergyserviceses) {
		this.useraccount = useraccount;
		this.localEnergyVendorName = localEnergyVendorName;
		this.localEnergyVendorDescription = localEnergyVendorDescription;
		this.zip = zip;
		this.localenergyserviceses = localenergyserviceses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LocalEnergyVendorId", unique = true, nullable = false)
	public Integer getLocalEnergyVendorId() {
		return this.localEnergyVendorId;
	}

	public void setLocalEnergyVendorId(Integer localEnergyVendorId) {
		this.localEnergyVendorId = localEnergyVendorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId")
	public Useraccount getUseraccount() {
		return this.useraccount;
	}

	public void setUseraccount(Useraccount useraccount) {
		this.useraccount = useraccount;
	}

	@Column(name = "LocalEnergyVendorName", nullable = false, length = 40)
	public String getLocalEnergyVendorName() {
		return this.localEnergyVendorName;
	}

	public void setLocalEnergyVendorName(String localEnergyVendorName) {
		this.localEnergyVendorName = localEnergyVendorName;
	}

	@Column(name = "LocalEnergyVendorDescription", length = 200)
	public String getLocalEnergyVendorDescription() {
		return this.localEnergyVendorDescription;
	}

	public void setLocalEnergyVendorDescription(String localEnergyVendorDescription) {
		this.localEnergyVendorDescription = localEnergyVendorDescription;
	}

	@Column(name = "Zip", nullable = false, length = 5)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localenergyvendor")
	public Set<Localenergyservices> getLocalenergyserviceses() {
		return this.localenergyserviceses;
	}

	public void setLocalenergyserviceses(Set<Localenergyservices> localenergyserviceses) {
		this.localenergyserviceses = localenergyserviceses;
	}

}
