package com.smartenergy.spring.pojo.hib1;
// Generated Apr 17, 2016 9:30:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Localconsumptionlist generated by hbm2java
 */
@Entity
@Table(name = "localconsumptionlist", catalog = "smartenergy2")
public class Localconsumptionlist implements java.io.Serializable {

	private LocalconsumptionlistId id;
	private Localenergyservices localenergyservices;
	private Consumer consumer;
	private float localVoltageConsumed;
	private Date fromDate;
	private Date toDate;
	private float rate;
	private float chargedAmount;

	public Localconsumptionlist() {
	}

	public Localconsumptionlist(LocalconsumptionlistId id, Localenergyservices localenergyservices, Consumer consumer,
			float localVoltageConsumed, Date fromDate, Date toDate, float rate, float chargedAmount) {
		this.id = id;
		this.localenergyservices = localenergyservices;
		this.consumer = consumer;
		this.localVoltageConsumed = localVoltageConsumed;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.rate = rate;
		this.chargedAmount = chargedAmount;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "localConsumptionId", column = @Column(name = "LocalConsumptionId", nullable = false)),
			@AttributeOverride(name = "localServicesId", column = @Column(name = "LocalServicesId", nullable = false)),
			@AttributeOverride(name = "localEnergyVendorId", column = @Column(name = "LocalEnergyVendorId", nullable = false)),
			@AttributeOverride(name = "consumerId", column = @Column(name = "ConsumerId", nullable = false)) })
	public LocalconsumptionlistId getId() {
		return this.id;
	}

	public void setId(LocalconsumptionlistId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "LocalServicesId", referencedColumnName = "LocalServicesId", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "LocalEnergyVendorId", referencedColumnName = "LocalEnergyVendorId", nullable = false, insertable = false, updatable = false) })
	public Localenergyservices getLocalenergyservices() {
		return this.localenergyservices;
	}

	public void setLocalenergyservices(Localenergyservices localenergyservices) {
		this.localenergyservices = localenergyservices;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ConsumerId", nullable = false, insertable = false, updatable = false)
	public Consumer getConsumer() {
		return this.consumer;
	}

	public void setConsumer(Consumer consumer) {
		this.consumer = consumer;
	}

	@Column(name = "LocalVoltageConsumed", nullable = false, precision = 12, scale = 0)
	public float getLocalVoltageConsumed() {
		return this.localVoltageConsumed;
	}

	public void setLocalVoltageConsumed(float localVoltageConsumed) {
		this.localVoltageConsumed = localVoltageConsumed;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fromDate", nullable = false, length = 10)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "toDate", nullable = false, length = 10)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	@Column(name = "Rate", nullable = false, precision = 12, scale = 0)
	public float getRate() {
		return this.rate;
	}

	public void setRate(float rate) {
		this.rate = rate;
	}

	@Column(name = "ChargedAmount", nullable = false, precision = 12, scale = 0)
	public float getChargedAmount() {
		return this.chargedAmount;
	}

	public void setChargedAmount(float chargedAmount) {
		this.chargedAmount = chargedAmount;
	}

}
