package com.smartenergy.spring.pojo.hib1;
// Generated Apr 17, 2016 9:30:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Useraccount generated by hbm2java
 */
@Entity
@Table(name = "useraccount", catalog = "smartenergy2")
public class Useraccount implements java.io.Serializable {

	private Integer userId;
	private Roles roles;
	private String userName;
	private String password;
	private Set<Localenergyvendor> localenergyvendors = new HashSet<Localenergyvendor>(0);
	private Set<Globalenergyvendor> globalenergyvendors = new HashSet<Globalenergyvendor>(0);
	private Set<Consumer> consumers = new HashSet<Consumer>(0);

	public Useraccount() {
	}

	public Useraccount(String userName, String password) {
		this.userName = userName;
		this.password = password;
	}

	public Useraccount(Roles roles, String userName, String password, Set<Localenergyvendor> localenergyvendors,
			Set<Globalenergyvendor> globalenergyvendors, Set<Consumer> consumers) {
		this.roles = roles;
		this.userName = userName;
		this.password = password;
		this.localenergyvendors = localenergyvendors;
		this.globalenergyvendors = globalenergyvendors;
		this.consumers = consumers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UserId", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RoleId")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@Column(name = "UserName", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Password", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "useraccount")
	public Set<Localenergyvendor> getLocalenergyvendors() {
		return this.localenergyvendors;
	}

	public void setLocalenergyvendors(Set<Localenergyvendor> localenergyvendors) {
		this.localenergyvendors = localenergyvendors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "useraccount")
	public Set<Globalenergyvendor> getGlobalenergyvendors() {
		return this.globalenergyvendors;
	}

	public void setGlobalenergyvendors(Set<Globalenergyvendor> globalenergyvendors) {
		this.globalenergyvendors = globalenergyvendors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "useraccount")
	public Set<Consumer> getConsumers() {
		return this.consumers;
	}

	public void setConsumers(Set<Consumer> consumers) {
		this.consumers = consumers;
	}

}
