/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BusinessIntelligence;

import Business.Business;
import Business.Customer;
import Business.Order;
import Business.OrderItem;
import Business.orderComparator;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neerajsing Rajput
 */
public class CustomerBySalesVolume extends javax.swing.JPanel {

    /**
     * Creates new form CustomerBySalesVolume
     */
    JPanel userProcessContainer;
    Business business;

    public CustomerBySalesVolume(JPanel upc, Business b) {
        initComponents();
        userProcessContainer = upc;
        business = b;
        getBestCustomer();
    }

    public void getBestCustomer() {
        DefaultTableModel dtm = (DefaultTableModel) customerBySalesTable.getModel();
        dtm.setRowCount(0);
        List<Order> orders;
        orders = new ArrayList<Order>();
        for (Customer c : business.getCustomerDirectory().getCustomerList()) {
            for (OrderItem oi : c.getOrder().getOrderItemList()) {
                Object row[] = new Object[2];
                row[0] = c.getCustomerName();
                row[1] = c.getOrder().getOrderTotal();
                orders.add(c.getOrder());
                dtm.addRow(row);
                c.getOrder().setCustomerName(c.getCustomerName());
                c.getOrder().setOrderTotal(c.getOrder().getOrderTotal());
            }
        }
        Order order;
        order = Collections.max(orders, new orderComparator());
        JOptionPane.showMessageDialog(null, "Maximum order items is " + order.getOrderTotal().toString() + "and it is by none other than " + order.getCustomerName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerBySalesTable = new javax.swing.JTable();

        customerBySalesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Customer Name", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(customerBySalesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customerBySalesTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
