/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BusinessIntelligence;

import Business.Business;
import Business.OrderItem;
import Business.Sales;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neerajsing Rajput
 */
public class SalesPersonAnalysis extends javax.swing.JPanel {

    /**
     * Creates new form SalesPersonAnalysis
     */
    JPanel userProcessContainer;
    Business business;
    Sales sales;

    public SalesPersonAnalysis(JPanel upc, Business b) {
        initComponents();
        userProcessContainer = upc;
        business = b;
        sales = new Sales();
        populateComboBox();

    }

    public void populateComboBox() {
        cmbSales.removeAllItems();
        for (Sales s : business.getSalesDirectory().getSalesList()) {
            cmbSales.addItem(s);
        }
    }

    public void populateTable() {

        DefaultTableModel dtm = (DefaultTableModel) productSoldAboveTarget.getModel();
        dtm.setRowCount(0);
        DefaultTableModel dtm1 = (DefaultTableModel) productSoldBelowTarget.getModel();
        dtm1.setRowCount(0);
        sales = (Sales) cmbSales.getSelectedItem();
        if (sales != null) {
            for (OrderItem oi : sales.getOrder().getOrderItemList()) {
                if (oi.getSalesPrice() > oi.getTargetPriceOfIndivual()) {
                    Object row[] = new Object[1];
                    row[0] = oi.getProduct();
                    dtm.addRow(row);
                } else {
                    Object row[] = new Object[1];
                    row[0] = oi.getProduct();
                    dtm1.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productSoldAboveTarget = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        productSoldBelowTarget = new javax.swing.JTable();
        cmbSales = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productSoldAboveTarget.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Products Sold Above Target Price"
            }
        ));
        jScrollPane1.setViewportView(productSoldAboveTarget);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, 375, 96));

        productSoldBelowTarget.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Products Sold Below Target Price"
            }
        ));
        jScrollPane2.setViewportView(productSoldBelowTarget);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 193, 370, 96));

        cmbSales.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSalesActionPerformed(evt);
            }
        });
        add(cmbSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 22, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSalesActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_cmbSalesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbSales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable productSoldAboveTarget;
    private javax.swing.JTable productSoldBelowTarget;
    // End of variables declaration//GEN-END:variables
}
