/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BusinessIntelligence;

import Business.Business;
import Business.Customer;
import Business.Order;
import Business.OrderItem;
import Business.Sales;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neerajsing Rajput
 */
public class Top3SalesPerson extends javax.swing.JPanel {

    /**
     * Creates new form Top3SalesPerson
     */
    JPanel userProcessContainer;
    Business business;

    public Top3SalesPerson(JPanel upc, Business b) {
        initComponents();
        userProcessContainer = upc;
        business = b;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) topSalesPersonTable.getModel();
        DefaultTableModel dtm1 = (DefaultTableModel) topSalesPersonTableViaSalesPerson.getModel();
        dtm.setRowCount(0);
        dtm1.setRowCount(0);
        ArrayList<Order> orders = new ArrayList<Order>();
        for (Sales s : business.getSalesDirectory().getSalesList()) {
            if (s.getOrder().getOrderTotal() > 0) {
                Object row[] = new Object[3];
                row[0] = s.getSalesName();
                row[1] = s.getOrder().getOrderTotal();
                dtm.addRow(row);
                s.getOrder().setSalesPersonName(s.getSalesName());
                orders.add(s.getOrder());
                //Weird shit here 
                s.getOrder().setOrderTotal(s.getOrder().getOrderTotal());
            }
        }
        //Calling of the sorting method
        Collections.sort(orders);
        for (Order afterSorting : orders) {
            Object row[] = new Object[2];
            row[0] = afterSorting.getSalesPersonName();
            row[1] = afterSorting.getOrderTotal();
            dtm1.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        topSalesPersonTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        topSalesPersonTableViaSalesPerson = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topSalesPersonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Sales Person", "Sales Volume"
            }
        ));
        jScrollPane3.setViewportView(topSalesPersonTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 25, 375, 93));

        topSalesPersonTableViaSalesPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Sales Person", "Sales Volume"
            }
        ));
        jScrollPane4.setViewportView(topSalesPersonTableViaSalesPerson);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 150, 375, 93));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable topSalesPersonTable;
    private javax.swing.JTable topSalesPersonTableViaSalesPerson;
    // End of variables declaration//GEN-END:variables
}
