/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdministrativeRole;

import Business.Drug;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Neerajsing Rajput
 */
public class AddDrug extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Drug drug;

    /**
     * Creates new form AddDrug
     */
    public AddDrug(JPanel upc, Drug d) {

        initComponents();
        userProcessContainer = upc;
        drug = d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtMfgDate = new javax.swing.JFormattedTextField();
        txtExpDate = new javax.swing.JFormattedTextField();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtAvailNum = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ADD DRUG ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 24, -1, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 67, -1, -1));

        jLabel4.setText("Price");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 146, -1, -1));

        jLabel5.setText("Mfg Date");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 174, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 64, 101, -1));
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 143, 101, -1));

        jLabel6.setText("Expiry Date");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 215, -1, -1));

        jButton2.setText("Add Drug");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 266, 119, -1));
        add(txtMfgDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 174, 101, -1));
        add(txtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 212, 101, -1));

        btnBack.setText("<<back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 266, 119, -1));

        jLabel7.setText("Available Number");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 105, -1, -1));
        add(txtAvailNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 102, 103, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        drug.setDrugName(txtName.getText());
        
        int price = -1;
        try {
            price = Integer.parseInt(txtPrice.getText());
            drug.setPrice(price);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Integer not entered");
            return;
        }

        String formattedStringDate = txtMfgDate.getText();
        Date date;
        try {
            date = new SimpleDateFormat("yyyy/MM/dd").parse(formattedStringDate);
            String stringformatDate = new SimpleDateFormat("yyyy/MM/dd").format(date);
            drug.setMfgDate(stringformatDate);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Date Not entered");
            return;
        }

        String formattedStringDate2 = txtExpDate.getText();

        try {
            date = new SimpleDateFormat("yyyy/MM/dd").parse(formattedStringDate2);
            String stringformatDate = new SimpleDateFormat("yyyy/MM/dd").format(date);
            drug.setExpiryDate(stringformatDate);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Date Not entered");
            return;
        }

        int availNumber = -1;
        try {
            availNumber = Integer.parseInt(txtAvailNum.getText());
            drug.setAvailNum(availNumber);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Integer not entered");
            return;
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
        refreshTable();
    }//GEN-LAST:event_btnBackActionPerformed
    private void refreshTable() {
        int index = userProcessContainer.getComponentCount() - 1;
        ManagePharmaDirectory panel = (ManagePharmaDirectory) userProcessContainer.getComponent(index);
        panel.populateDrugCatalogAsPharma();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAvailNum;
    private javax.swing.JFormattedTextField txtExpDate;
    private javax.swing.JFormattedTextField txtMfgDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
