/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdministrativeRole;

import Business.CVS;
import Business.Store;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Neerajsing Rajput
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    CVS cvsAdmin;

    /**
     * Creates new form AdminWorkAreaPanel
     */
    public AdminWorkAreaPanel(JPanel upc, CVS cvs) {
        initComponents();
        userProcessContainer = upc;
        cvsAdmin = cvs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCVSAdmin = new javax.swing.JButton();
        btnStoreAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCVSAdmin.setText("CVS Admin");
        btnCVSAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCVSAdminActionPerformed(evt);
            }
        });
        add(btnCVSAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 81, 132, -1));

        btnStoreAdmin.setText("Store Admin");
        btnStoreAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreAdminActionPerformed(evt);
            }
        });
        add(btnStoreAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 115, 132, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Admin Work Area Panel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCVSAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCVSAdminActionPerformed
        // TODO add your handling code here:
        CVSAdminWorkAreaPanel panel = new CVSAdminWorkAreaPanel(userProcessContainer, cvsAdmin);
        userProcessContainer.add("CVSAdminWorkAreaPanel", panel);
        CardLayout cradlayout = (CardLayout) userProcessContainer.getLayout();
        cradlayout.next(userProcessContainer);

    }//GEN-LAST:event_btnCVSAdminActionPerformed

    private void btnStoreAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreAdminActionPerformed
        // TODO add your handling code here:
        //Logic to select stores via cvs Admin

        if (!cvsAdmin.getStores().getStoreList().isEmpty()) {
            ArrayList<String> getLocationOfStores = new ArrayList<>();
            for (int i = 0; i < cvsAdmin.getStores().getStoreList().size(); i++) {
                Store ss = cvsAdmin.getStores().getStoreList().get(i);
                getLocationOfStores.add(ss.getStoreLocation());
            }
            Object[] selectedStoreLocationOption = getLocationOfStores.toArray();
            String selectedStore = (String) JOptionPane.showInputDialog(null, "Please select the store for the Admin \n", "Options", JOptionPane.PLAIN_MESSAGE, null, selectedStoreLocationOption, "");
            if (selectedStore != null && !selectedStore.isEmpty()) {
                Store storeLocation = cvsAdmin.getStores().searchStore(selectedStore);
                StoreAdminWorkAreaPanel panel = new StoreAdminWorkAreaPanel(userProcessContainer, storeLocation,cvsAdmin.getPharmaDirectory());
                userProcessContainer.add("StoreAdminWorkAreaPanel", panel);
                CardLayout cradlayout = (CardLayout) userProcessContainer.getLayout();
                cradlayout.next(userProcessContainer);
            } else {
                JOptionPane.showMessageDialog(null, "The store has to be selected to view the inventory");
            }
        }
        else{
        JOptionPane.showMessageDialog(null, "There are no stores!!!");
        }


    }//GEN-LAST:event_btnStoreAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCVSAdmin;
    private javax.swing.JButton btnStoreAdmin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
