/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdministrativeRole;

import Business.Pharma;
import Business.PharmaDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author Neerajsing Rajput
 */
public class CreatePharmaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePharmaJPanel
     */
    JPanel userProcessContainer;
    PharmaDirectory pharmaDirectory;

    public CreatePharmaJPanel(JPanel u, PharmaDirectory pd) {
        initComponents();
        userProcessContainer = u;
        pharmaDirectory = pd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPharmaName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pharma");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 55, -1, -1));
        add(txtPharmaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 52, 101, -1));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 112, -1, -1));

        jButton2.setText("<<back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 112, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Create Pharma");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 11, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
        refreshTable();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void refreshTable() {
        int index = userProcessContainer.getComponentCount() - 1;
        ManagePharmaDirectory panel = (ManagePharmaDirectory) userProcessContainer.getComponent(index);
        panel.populatePharmaComboBox();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String pharmaName = txtPharmaName.getText();

        boolean pharmaLocationAlreadyPresent = false;

        for (Pharma p : pharmaDirectory.getPharmaList()) {
            if (pharmaName.equals(p.getPharmaName())) {
                pharmaLocationAlreadyPresent = true;
            } else {
                pharmaLocationAlreadyPresent = false;
            }

        }
        if (pharmaLocationAlreadyPresent || pharmaName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pharma is duplicate or empty");
        } else {
            Pharma pharma = pharmaDirectory.createPharma();
            pharma.setPharmaName(pharmaName);
            JOptionPane.showMessageDialog(null, "Pharma stored Successfully!!!");
            txtPharmaName.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPharmaName;
    // End of variables declaration//GEN-END:variables
}
