/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdministrativeRole;

import Business.CVS;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Neerajsing Rajput
 */
public class CVSAdminWorkAreaPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    CVS cvsAdmin;

    /**
     * Creates new form CVSAdminWorkAreaPanel
     */
    public CVSAdminWorkAreaPanel(JPanel upc, CVS cvs) {
        initComponents();
        userProcessContainer = upc;
        cvsAdmin = cvs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnCreatePharma = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Create CVS Store");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 100, 137, -1));

        jButton3.setText("Browse Inventory");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 141, 137, -1));

        btnCreatePharma.setText("Manage Pharma");
        btnCreatePharma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePharmaActionPerformed(evt);
            }
        });
        add(btnCreatePharma, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 59, 137, -1));

        jButton1.setText("<<back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CVS Admin Work Area Panel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 19, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CreateCVSStoreJPanel panel = new CreateCVSStoreJPanel(userProcessContainer, cvsAdmin.getStores());
        userProcessContainer.add("CreateCVSStoreJPanel", panel);
        CardLayout cradlayout = (CardLayout) userProcessContainer.getLayout();
        cradlayout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ManageStoreJPanel panel = new ManageStoreJPanel(userProcessContainer, cvsAdmin.getStores());
        userProcessContainer.add("ManageStoreJPanel", panel);
        CardLayout cradlayout = (CardLayout) userProcessContainer.getLayout();
        cradlayout.next(userProcessContainer);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCreatePharmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePharmaActionPerformed
        // TODO add your handling code here:
        ManagePharmaDirectory panel = new ManagePharmaDirectory(userProcessContainer, cvsAdmin.getPharmaDirectory());
        userProcessContainer.add("ManagePharmaDirectory", panel);
        CardLayout cradlayout = (CardLayout) userProcessContainer.getLayout();
        cradlayout.next(userProcessContainer);

    }//GEN-LAST:event_btnCreatePharmaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePharma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
