/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdministrativeRole;

import Business.DrugItem;
import Business.Inventory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neerajsing Rajput
 */
public class InventoryReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryReportJPanel
     */
    JPanel userProcessContainer;
    Inventory inventory;
    private static final int THRESHOLD = 10;

    public InventoryReportJPanel(JPanel upc, Inventory i) {
        initComponents();
        userProcessContainer = upc;
        inventory = i;
        populateDrugItemList();
    }

    public void populateDrugItemList() {
        DefaultTableModel dtm = (DefaultTableModel) txtDrugItemList.getModel();
        dtm.setRowCount(0);

        for (DrugItem drugitem : inventory.getDrugItemList()) {
            Object[] row = createRow(drugitem);
            dtm.addRow(row);
        }
    }

    private Object[] createRow(DrugItem drugItem) {
        if (drugItem.getQuantity() < THRESHOLD) {
            drugItem.setSupplyAlert("Get More Drugs");
        } else {
            drugItem.setSupplyAlert("No need for more drugs");
        }
        Object[] row = new Object[3];
        row[0] = drugItem;
        row[1] = drugItem.getQuantity();
        row[2] = drugItem.getSupplyAlert();
        return row;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDrugItemList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Inventory Reporting");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 25, -1, -1));

        txtDrugItemList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug", "Quantity", "Status"
            }
        ));
        jScrollPane1.setViewportView(txtDrugItemList);
        if (txtDrugItemList.getColumnModel().getColumnCount() > 0) {
            txtDrugItemList.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 464, 98));

        jButton1.setText("<<back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 177, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable txtDrugItemList;
    // End of variables declaration//GEN-END:variables
}
