/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdministrativeRole;

import Business.Drug;
import Business.Pharma;
import Business.PharmaDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neerajsing Rajput
 */
public class ManagePharmaDirectory extends javax.swing.JPanel {

    JPanel userProcessContainer;
    PharmaDirectory pharmaDirectory;

    /**
     * Creates new form ManagePharmaDirectory
     */
    public ManagePharmaDirectory(JPanel u, PharmaDirectory pd) {
        initComponents();
        userProcessContainer = u;
        pharmaDirectory = pd;
        populatePharmaComboBox();
        populateDrugCatalogAsPharma();
    }

    public void populatePharmaComboBox() {
        storeBoxPharma.removeAllItems();
        for (Pharma pharma : pharmaDirectory.getPharmaList()) {
            storeBoxPharma.addItem(pharma);
        }
    }

    public void populateDrugCatalogAsPharma() {
        DefaultTableModel dtm = (DefaultTableModel) tblDrugCatalog.getModel();
        dtm.setRowCount(0);

        Pharma pharma = (Pharma) storeBoxPharma.getSelectedItem();

        if (pharma != null) {
            for (Drug drug : pharma.getDrugCatalog().getDrugList()) {
                Object[] row = createRow(drug);
                dtm.addRow(row);
            }
        }
    }

    private Object[] createRow(Drug drug) {
        Object[] row = new Object[5];
        row[0] = drug;
        row[1] = drug.getAvailNum();
        row[2] = drug.getPrice();
        row[3] = drug.getMfgDate();
        row[4] = drug.getExpiryDate();
        
        return row;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPharmaAdd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDrugCatalog = new javax.swing.JTable();
        storeBoxPharma = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtAddDrug = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPharmaAdd.setText("Add Pharma");
        btnPharmaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPharmaAddActionPerformed(evt);
            }
        });
        add(btnPharmaAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jButton1.setText("<<back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jButton3.setText("View Drug Catalog");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 133, -1));

        tblDrugCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Drug Name", "Avail Number", "Price", "MFG Date", "Expiry Date"
            }
        ));
        jScrollPane2.setViewportView(tblDrugCatalog);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 410, 90));

        storeBoxPharma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(storeBoxPharma, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 181, -1));

        jLabel1.setText("Pharma");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        txtAddDrug.setText("Add Drug");
        txtAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddDrugActionPerformed(evt);
            }
        });
        add(txtAddDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Manage PharmaDirectory and DrugCatalog");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPharmaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPharmaAddActionPerformed
        // TODO add your handling code here:
        CreatePharmaJPanel panel = new CreatePharmaJPanel(userProcessContainer, pharmaDirectory);
        userProcessContainer.add("ManagePharmaDirectory", panel);
        CardLayout cradlayout = (CardLayout) userProcessContainer.getLayout();
        cradlayout.next(userProcessContainer);
    }//GEN-LAST:event_btnPharmaAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        populateDrugCatalogAsPharma();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddDrugActionPerformed
        // TODO add your handling code here:
        Pharma pharma = (Pharma) storeBoxPharma.getSelectedItem();
        if (pharma != null) {
        AddDrug panel = new AddDrug(userProcessContainer, pharma.getDrugCatalog().createDrug());
        userProcessContainer.add("AddDrug", panel);
        CardLayout cradlayout = (CardLayout) userProcessContainer.getLayout();
        cradlayout.next(userProcessContainer);
        }
    }//GEN-LAST:event_txtAddDrugActionPerformed
    private Object selectedItemInTable(JTable table) {
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            Object object = table.getValueAt(selectedRow, 0);
            return object;
        } else {
            JOptionPane.showMessageDialog(null, "No item selected");
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPharmaAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox storeBoxPharma;
    private javax.swing.JTable tblDrugCatalog;
    private javax.swing.JButton txtAddDrug;
    // End of variables declaration//GEN-END:variables
}
